# The URL the site will be built for
base_url = "https://www.tokyoscale.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

taxonomies = [
    {name = "categories"},
    {name = "tags", paginate_by = 5, rss = true},
    {name = "authors", rss = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customized by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
